"""create agent_templates table

Revision ID: 08fdd9291d58
Revises: baea3a30dac6
Create Date: 2026-08-22 13:41:37.289906+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fdd9291d58'
down_revision: Union[str, None] = 'baea3a30dac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'GROQ', 'OLLAMA', name='provider', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='4096', nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='visibility', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_official', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'HIDDEN', name='moderationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_templates_category', 'agent_templates', ['category'], unique=False)
    op.create_index(op.f('ix_agent_templates_id'), 'agent_templates', ['id'], unique=False)
    op.create_index('ix_agent_templates_moderation_status', 'agent_templates', ['moderation_status'], unique=False)
    op.create_index('ix_agent_templates_owner_id', 'agent_templates', ['owner_id'], unique=False)
    op.create_index('ix_agent_templates_visibility', 'agent_templates', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_templates_visibility', table_name='agent_templates')
    op.drop_index('ix_agent_templates_owner_id', table_name='agent_templates')
    op.drop_index('ix_agent_templates_moderation_status', table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_id'), table_name='agent_templates')
    op.drop_index('ix_agent_templates_category', table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
